name: CMake

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - run: pwsh ci_prebuild.ps1
    - run: pwsh cmake_build.ps1
    - run: pwsh cmake_afterbuild.ps1 
