name: documentation
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup python
        uses: actions/setup-python@v3
        with:
          cache: "pip"

      - name: install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: build
        run: |
          pushd docs
          make html
          popd

      - name: commit
        run: |
          pushd docs
          cd _build/html
          git init
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'deploy'
          popd
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          directory: docs/_build/html
