name: CMake

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache vcpkg
        id: cache-vcpkg
        uses: actions/cache@v2
        with:
          path: |
            C:/vcpkg/
            !C:/vcpkg/buildtrees
          key: ${{ runner.os }}-cache

      - name: Install ninja-build tool
        uses: seanmiddleditch/gha-setup-ninja@v3
      - uses: ilammy/msvc-dev-cmd@v1

      - uses: actions/setup-python@v2
        with:
          python-version: "3.8.10"
          architecture: "x64"

      - name: Install dependencies
        run: |
          Push-Location C:/vcpkg
          .\bootstrap-vcpkg.bat
          .\vcpkg install fmt boost-json boost-asio boost-beast boost-filesystem `
            boost-process boost-python --triplet x64-windows
          Pop-Location

      - uses: actions/cache@v2
        id: cache-qt
        with:
          path: '${{ github.workspace }}/Qt'
          key: ${{ runner.os }}-qt
  
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with: 
          dir: '${{ github.workspace }}/'
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: cmake configure
        run: |
          Push-Location src/qt
          $Env:CMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake"
          cmake -B ../../build -G "Ninja" -Wno-dev
          Pop-Location

      - name: cmake build
        run: |
          cmake --build build

      - name: copy dependencies
        run: |
          $dest = "bin"
          Write-Host "copying to $dest"

          if (Test-Path -Path $dest) {
              Remove-Item -Path $dest/* -Recurse
          }

          New-Item -ItemType Directory -Path $dest -Force

          Copy-Item -Path build/*.exe $dest
          Copy-Item -Path build/*.dll $dest

          Copy-Item -Path CHANGELOG.md $dest

          Copy-Item -Path HCNetSDK/lib_win64/*.dll -Destination $dest -Recurse -Force
          Copy-Item -Path HCNetSDK/lib_win64/HCNetSDKCom -Destination $dest -Recurse -Force

          Push-Location C:/Windows/System32/
          Copy-Item -Path `
              msvcp140d.dll, VCRUNTIME140D.dll, VCRUNTIME140_1D.dll, ucrtbased.dll `
              -Destination $dest
          Pop-Location

          Copy-Item `
              -Path src/configurations/Default.ini, src/configurations/程序配置.ini `
              -Destination $dest

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: binary
          path: bin
